/*
Navicat MySQL Data Transfer

Source Server         : ERP
Source Server Version : 50173
Source Host           : 192.168.163.50:3306
Source Database       : ERP

Target Server Type    : MYSQL
Target Server Version : 50173
File Encoding         : 65001

Date: 2017-02-28 13:51:32
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for BASE_DEPOT_CONF
-- ----------------------------
DROP TABLE IF EXISTS `BASE_DEPOT_CONF`;
CREATE TABLE `BASE_DEPOT_CONF` (
  `ID` varchar(20) NOT NULL DEFAULT '主键',
  `DEPOT_CODE` varchar(20) DEFAULT '库房编号' COMMENT '库房编号',
  `TYPE` varchar(20) DEFAULT '库房类型' COMMENT '库房类型',
  `NAME` varchar(20) DEFAULT '库房名称' COMMENT '库房名称',
  `ENGLISH_NAME` varchar(20) DEFAULT '库房英文名称' COMMENT '库房英文名称',
  `LOCATION` varchar(20) DEFAULT '物理位置' COMMENT '物理位置',
  `BUIT_IN` varchar(20) DEFAULT '物理位置' COMMENT '是否内置库房0：否1：是',
  `CREATE_TIME` varchar(20) DEFAULT '创建时间' COMMENT '创建时间',
  `LAST_UPDATE` varchar(20) DEFAULT '更新时间' COMMENT '更新时间',
  `RE_VARCHAR_0` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_0',
  `RE_VARCHAR_1` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_1',
  `RE_VARCHAR_2` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_2',
  `RE_VARCHAR_3` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_3',
  `RE_VARCHAR_4` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_4',
  `RE_VARCHAR_5` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_5',
  `RE_VARCHAR_6` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_6',
  `RE_VARCHAR_7` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_7',
  `RE_VARCHAR_8` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_8',
  `RE_VARCHAR_9` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_9',
  `RE_VARCHAR_10` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_10',
  `RE_VARCHAR_11` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_11',
  `RE_VARCHAR_12` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_12',
  `RE_VARCHAR_13` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_13',
  `RE_VARCHAR_14` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_14',
  `RE_VARCHAR_15` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_15',
  `RE_VARCHAR_16` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_16',
  `RE_VARCHAR_17` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_17',
  `RE_VARCHAR_18` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_18',
  `RE_VARCHAR_19` varchar(255) DEFAULT NULL COMMENT 'RE_VARCHAR_19',
  `RE_INT_0` varchar(255) DEFAULT NULL COMMENT 'RE_INT_0',
  `RE_INT_1` varchar(255) DEFAULT NULL COMMENT 'RE_INT_1',
  `RE_INT_2` varchar(255) DEFAULT NULL COMMENT 'RE_INT_2',
  `RE_INT_3` varchar(255) DEFAULT NULL COMMENT 'RE_INT_3',
  `RE_INT_4` varchar(255) DEFAULT NULL COMMENT 'RE_INT_4',
  `RE_DOUBLE_0` varchar(255) DEFAULT NULL COMMENT 'RE_DOUBLE_0',
  `RE_DOUBLE_1` varchar(255) DEFAULT NULL COMMENT 'RE_DOUBLE_1',
  `RE_DOUBLE_2` varchar(255) DEFAULT NULL COMMENT 'RE_DOUBLE_2',
  `RE_DOUBLE_3` varchar(255) DEFAULT NULL COMMENT 'RE_DOUBLE_3',
  `RE_DOUBLE_4` varchar(255) DEFAULT NULL COMMENT 'RE_DOUBLE_4',
  `RE_DATE_0` varchar(255) DEFAULT NULL COMMENT 'RE_DATE_0',
  `RE_DATE_1` varchar(255) DEFAULT NULL COMMENT 'RE_DATE_1',
  `RE_DATE_2` varchar(255) DEFAULT NULL COMMENT 'RE_DATE_2',
  `RE_DATE_3` varchar(255) DEFAULT NULL COMMENT 'RE_DATE_3',
  `RE_DATE_4` varchar(255) DEFAULT NULL COMMENT 'RE_DATE_4',
  `RE_DATETIME_0` varchar(255) DEFAULT NULL COMMENT 'RE_DATETIME_0',
  `RE_DATETIME_1` varchar(255) DEFAULT NULL COMMENT 'RE_DATETIME_1',
  `RE_DATETIME_2` varchar(255) DEFAULT NULL COMMENT 'RE_DATETIME_2',
  `RE_DATETIME_3` varchar(255) DEFAULT NULL COMMENT 'RE_DATETIME_3',
  `RE_DATETIME_4` varchar(255) DEFAULT NULL COMMENT 'RE_DATETIME_4',
  `RE_LONGTEXT_0` varchar(255) DEFAULT NULL COMMENT 'RE_LONGTEXT_0',
  `RE_LONGTEXT_1` varchar(255) DEFAULT NULL COMMENT 'RE_LONGTEXT_1',
  `RE_LONGTEXT_2` varchar(255) DEFAULT NULL COMMENT 'RE_LONGTEXT_2',
  `RE_LONGTEXT_3` varchar(255) DEFAULT NULL COMMENT 'RE_LONGTEXT_3',
  `RE_LONGTEXT_4` varchar(255) DEFAULT NULL COMMENT 'RE_LONGTEXT_4',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='库房类型表中文名称表';

-- ----------------------------
-- Records of BASE_DEPOT_CONF
-- ----------------------------
INSERT INTO `BASE_DEPOT_CONF` VALUES ('1', '库房编号', '库房类型', '库房名称',库房英文名称', '物理位置', '物理位置', '创建时间', '更新时间', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
